wso2/carbon-ui-server

pom.xml

Fixes issue #4.
This PR removes the `<maven.bundle.plugin.version>` variable from root `pom.xml` which overwrote the value (3.0.0) from WSO2 parent pom.

Bump Maven Bundle plugin version to 3.0.0

---

components/core/pom.xml
components/core/src/main/java/org/wso2/carbon/uis/internal/http/Msf4jHttpConnector.java

As a workaround for "Server doesn't start-up after installing Dashboard features", this PR introduces necessary changes to delay microservices deployment until Carbon server fully starts.
Carbon server is considered as fully started when `org.wso2.carbon.kernel.utils.CarbonServerInfo` OSGi service is available.

Add CarbonServerInfo OSGi reference to Msf4jHttpConnector class

---

features/org.wso2.carbon.uis.feature/src/main/resources/README.txt
features/org.wso2.carbon.uis.feature/src/main/resources/p2.inf
tests/distribution/pom.xml
tests/distribution/src/assembly/bin.xml

`org.wso2.carbon.uis.feature` feature does not create following directories upon installation.
- `<carbon_home>/deployment/web-ui-apps/`
- `<carbon_home>/wso2/<runtime>/deployment/web-ui-apps/`
Fixes #26 
`org.wso2.carbon.uis.feature` feature should create said directories in the install phase.
Create directories using `p2.inf`.
1.8.0_144

Create web-ui-apps directory when installing org.wso2.carbon.uis.feature

---

components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppCreator.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/reference/ArtifactAppReference.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/reference/AppReference.java

Currently `configuration.yaml` file is mandatory in a web app.
Fixes #27 
Make `configuration.yaml` optional.
If `configuration.yaml` file doesn't exists, create an empty configuration object.
JDK 1.8.0_144

Make configuration.yaml file optional in a web app

---

components/org.wso2.carbon.uis/pom.xml
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/App.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/Page.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/exception/RenderingException.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppCreator.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/impl/HbsPage.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/impl/HtmlPage.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/api/AppTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/api/PageTest.java
features/org.wso2.carbon.uis.feature/pom.xml
pom.xml
tests/distribution/carbon-home/deployment/web-ui-apps/test/pages/index.hbs

As discussed in the "[Option for the customer to change the app context path in React based web apps](http://markmail.org/message/7ovuikaduq3wly2i)" architecture mail thread, Carbon UI Server needs support to render pages written with Handlebars.
Support for render Handlebars pages (e.g.`index.hbs`). Following Handlebars context variables will be supported.
- `@contextPath`
```hbs
<link href="{{@contextPath}}/public/app/css/styles.css" />
<script src="{{@contextPath}}/public/app/js/bundle.js"></script>
<link …
```

Add Handlebars support

---

components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/Msf4jHttpConnector.java

Once a web app get registered to the transport, it does not get unregistered when it is undeployed.
Fixes #35 
Web app should get unregistered from the transport when it is undeployed.
Instead of `SetMultimap.get(key)` use `SetMultimap.removeAll(key)` in `Msf4jHttpConnector.unregisterApp(appName)` method.

Fix bug of not unregistering web apps from transport when they are undeployed

---

components/org.wso2.carbon.uis/pom.xml
features/org.wso2.carbon.uis.feature/pom.xml
pom.xml
tests/distribution/pom.xml
tests/pom.xml

Need to migrate to Carbon Kernel v5.2.0. Also need to migrate to MSF4J v2.4.2 for necessary bug fixes.
Following dependencies will be bumped to respective versions.
- MSF4J v2.4.2
- carbon-messaging v3.0.1
- carbon-transport v5.0.1
- carbon-metrics v2.3.2
- carbon-jndi v1.0.4
- carbon-datasources v1.1.3
- carbon-deployment v5.1.5
- carbon-config to v2.1.2
- carbon-kernel to v5.2.0
Also bumps the repo version to 0.11.0-SNAPSHOT

Bump dependency versions to newer

---

components/org.wso2.carbon.uis/pom.xml
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/Configuration.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/RequestDispatcher.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppCreator.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/ConfigurationYaml.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/parser/YamlFileParser.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/exception/ConfigurationException.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/StaticResolver.java
features/org.wso2.carbon.uis.feature/pom.xml
pom.xml
tests/distribution/carbon-home/wso2/default/deployment/web-ui-apps/test/configuration.yaml

Currently `configuration.yaml` file of a web app is not loaded (see [`AppCreator.createConfiguration(FileReference fileReference)`](https://github.com/wso2/carbon-ui-server/blob/v0.12.0/components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppCreator.java#L124))
If exists, load & consume `configuration.yaml` file of a web app.
- Added `ConfigurationYaml` class that acts as the bean class for `configuration.yaml` file.
- Refactored `Configuration` class.
`configuration.yaml`
```yaml
httpsOnly: true
responseHeaders:
resources:
"Content-Security-Policy": "default-src 'none'; script-src 'self' ssl.google-analytics.com;"
pages:
"X-Frame-Options": "DENY"
```
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? …

Load configuration.yaml file in a web app

---

components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/Configuration.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/http/HttpConnector.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/CarbonUiServer.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppCreator.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/Msf4jHttpConnector.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/impl/OverriddenApp.java

Currently `httpsOnly` configuration value in the `configuration.yaml` file of a web app, is not honored when registering web apps to transport layer.
Fixes #33 
If `httpsOnly` is `true` then that web app should be only be deployed to HTTPS transports. If `false` then register to all HTTP transports.
Change parameters of `registerApp` method of `HttpConnector` interface to accept registering  `App` object.
```java
void registerApp(App app, Function<HttpRequest, HttpResponse> httpListener);
```
In `Msf4jHttpConnector.registerApp` method, get app's configuration and check for the `httpsOnly` configuration (`app.getConfiguration().isHttpsOnly()`). If that is `true` then register only for HTTPS transports.
`configuration.yaml`
```yaml
httpsOnly: true
```
- Followed secure coding standards in …

Enable `httpsOnly` configuration in the `configuration.yaml` of a web app

---

components/org.wso2.carbon.uis/pom.xml
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/ServerConfiguration.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/CarbonUiServer.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/Msf4jHttpConnector.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/deployment/ArtifactAppDeployer.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/api/ServerConfigurationTest.java
pom.xml
tests/distribution/carbon-home/conf/default/deployment.yaml
tests/distribution/pom.xml

Fixes #47 
Load Carbon UI Server configurations to `ServerConfiguration` from `deployment.yaml`.
`deployment.yaml`:
```yaml
wso2.carbon-ui-server:
contextPaths:
"portal": "my-dashboard"
"monitor": "sys-status"
```
- Unit tests 
- Added tests for `org.wso2.carbon.uis.api.ServerConfiguration` class.
- Coverage: 42%
N/A
See `tests/distribution/carbon-home/conf/default/deployment.yaml`

Override context path of a web app via the deployment.yaml

---

components/org.wso2.carbon.uis/pom.xml
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/http/HttpResponse.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/RequestDispatcher.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/ResponseBuilder.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/StaticResolver.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/api/http/HttpResponseTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/http/ResponseBuilderTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/io/StaticResolverTest.java
features/org.wso2.carbon.uis.feature/pom.xml
pom.xml
tests/distribution/pom.xml
tests/pom.xml

Currently `org.wso2.carbon.uis.api.http.HttpResponse` class is not immutable, which might lead to concurrent issues.
Make `HttpResponse` class immutable.
- Removed all getters from `HttpResponse`.
- Added `org.wso2.carbon.uis.internal.http.ResponseBuilder` class for convenience.
- Bumped repo version to `0.13.0`.
- Unit tests 
Added unit tests for `HttpResponse`, `ResponseBuilder` classes.
Code coverage: 45%
N/A

Make `HttpResponse` class immutable

---

components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppCreator.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/reference/ArtifactAppReference.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/deployment/AppCreatorTest.java

Fixes #52
If a web app does not have the `pages` directory or any pages, then do not deploy that web app.
- If `pages` directory is missing, throw a file operation exception.
- If there are no pages, then throw an app creation exception.
- Unit tests 
Improved `AppCreatorTest`
Code coverage: 45%
N/A

Make having a page mandatory in a web app to be deployed

---

pom.xml

- Update the gson package version to 2.7 and update the version rage upto 3.0
- To fix the OSGI Gson bundle conflicts with APIM 3.0.0
- java version "1.8.0_151"
- APIM 3.0 M9
- Ubuntu 16.04.3 LTS (xenial)

Update Google gson version

---

components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/App.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/Page.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/RequestDispatcher.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/exception/BadRequestException.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/PageRequestDispatcher.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/StaticRequestDispatcher.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/RequestDispatcherTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/http/PageRequestDispatcherTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/io/StaticRequestDispatcherTest.java

- Simplify logic in [`StaticResolver`](https://github.com/wso2/carbon-ui-server/blob/v0.13.3/components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/StaticResolver.java) class and [`RequestDispatcher`](https://github.com/wso2/carbon-ui-server/blob/v0.13.3/components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/RequestDispatcher.java)
- Improve test coverage on HTTP request dispatching logic
- Improve exception handling (currently some exceptions might slip-through if happens)
- Eliminate possible bugs
-  Add `PageRequestDispatcher` class which dispatches HTTP requests for pages.
- Rename `StaticResolver` to `StaticRequestDispatcher` which dispatches HTTP requests for static resources.
- Changed logic in `RequestDispatcher` class to delegate HTTP …

Refactoring HTTP request dispatching logic

---

components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/msf4j/Msf4jHttpConnector.java
pom.xml

$subject
- Bumped Carbon Kenel version to v5.2.5
- Set `skipCarbonStartupResolver` to `true` when registering microservices.

Bump Carbon Kernel version to v5.2.5

---

components/org.wso2.carbon.uis/pom.xml
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/RestApiDeployer.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/spi/RestApiProvider.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/deployment/RestApiDeployerTest.java
features/org.wso2.carbon.uis.feature/pom.xml
pom.xml
tests/distribution/pom.xml
tests/pom.xml

The only way to acquire an `org.wso2.carbon.uis.api.App` object of a web app is by getting a reference to the `org.wso2.carbon.uis.spi.Server` OSGi service. `org.wso2.carbon.uis.spi.Server` OSGi service is activated after all available `org.wso2.carbon.uis.spi.RestApiProvider` are activated and `org.wso2.msf4j.MicroservicesServer` service is activated. Hence, a circular OSGi dependency can occur if a Microservice of a web app needs to get access to the associated web app object.
A Microservice of a web app should be able to get the `org.wso2.carbon.uis.api.App` object of the associated web app.
- Changed `Map<String, Microservice> getMicroservices()` method in `org.wso2.carbon.uis.spi.RestApiProvider` interface to `Map<String, Microservice> getMicroservices(App app)`
- Bump repo version …

Add an App parameter to getMicroservices() method in RestApiProvider interface

---

pom.xml

- Bump MSF4J verstion to v2.5.0-beta2
- Bump transport.http.netty version to v6.0.56

Bump MSF4J verstion to v2.5.0-beta2

---

components/org.wso2.carbon.uis/pom.xml
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/Configuration.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/api/ServerConfiguration.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/StartupListener.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppDeploymentEventListener.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/AppTransportBinder.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/RestApiDeployer.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/deployment/parser/ConfigurationYaml.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/exception/AppDeploymentEventListenerException.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/HttpTransport.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/msf4j/MicroserviceRegistration.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/msf4j/MicroservicesRegistrar.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/http/util/IpAddressUtils.java
components/org.wso2.carbon.uis/src/main/java/org/wso2/carbon/uis/internal/io/deployment/ArtifactAppDeployer.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/api/ConfigurationTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/api/ServerConfigurationTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/deployment/AppTransportBinderTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/deployment/RestApiDeployerTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/http/HttpTransportTest.java
components/org.wso2.carbon.uis/src/test/java/org/wso2/carbon/uis/internal/http/msf4j/MicroserviceRegistrationTest.java
components/org.wso2.carbon.uis/src/test/resources/apps/full-app/configuration.yaml
features/org.wso2.carbon.uis.feature/pom.xml
pom.xml
tests/distribution/carbon-home/conf/default/deployment.yaml
tests/distribution/carbon-home/wso2/default/deployment/web-ui-apps/test/configuration.yaml
tests/distribution/pom.xml
tests/pom.xml

Currently there is no option to deploy a web app to a specific HTTP transport.
$subject
- Change the `ServerConfiguration` class to accept following new configurations from `deployment.yaml`
```yaml
wso2.carbon-ui-server:
apps:
<app_name>:
contextPath: <app_context_path>
transportId: <transport_id>
<another_app_name>:
transportId: <another_transport_id>
wso2.transport.http:
listenerConfigurations:
- id: <transport_id>
host: "0.0.0.0"
port: 9090
- id:<another_transport_id>
host: "0.0.0.0"
port: 9443
scheme: https
keyStoreFile: "${carbon.home}/resources/security/wso2carbon.jks"
keyStorePassword: wso2carbon
certPass: wso2carbon
senderConfigurations:
- id: "default-http-sender"
```
- Remove redundant `httpsOnly: true` configuration from `configuration.yaml` of in web apps.
- Bump repo version …

Option to deploy a web app exclusively to a configured HTTP transport

---

pom.xml

- Bump MSF4J version to v2.5.1
- Bump transport.http version to v6.0.64
- Bump carbon.deployment version to v5.1.9

Bump MSF4J version to v2.5.1

---

components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/api/exception/HttpErrorException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/api/exception/RenderingException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/api/exception/UiServerException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/api/exception/UiServerRuntimeException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/exception/AppCreationException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/exception/AppDeploymentEventListenerException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/exception/FileOperationException.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/http/RequestDispatcher.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/io/util/MimeMapper.java
components/org.wso2.carbon.uiserver/src/test/java/org/wso2/carbon/uiserver/internal/http/RequestDispatcherTest.java
tests/distribution/pom.xml

Rename UISException class to UiServerException and UISRuntimeException class to UiServerRuntimeException, as [suggested in code review](https://groups.google.com/a/wso2.com/d/msg/engineering-group/aMA_U4QCjN4/s5uBWGGUCQAJ).
- Renames following classes
- UISException --> **UiServerException**
- UISRuntimeException --> **UiServerRuntimeException**

Rename UISException, UISRuntimeException classes

---

components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/deployment/AppCreator.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/io/deployment/ArtifactAppDeployer.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/io/reference/ArtifactAppReference.java
components/org.wso2.carbon.uiserver/src/test/java/org/wso2/carbon/uiserver/internal/deployment/AppCreatorTest.java
pom.xml

Bump carbon deployment version to v5.2.0

Bump Carbon Deployment version to v5.2.0

---

components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/deployment/listener/AppTransportBinder.java
components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/deployment/listener/RestApiDeployer.java
pom.xml

This PR adds the capability to have multiple `RestApiProvider`s for the same webapp.
- Unit tests 
Code coverage: 66%
N/A

Allow multiple 'RestApiProvider's for the same webapp

---

components/org.wso2.carbon.uiserver/src/main/java/org/wso2/carbon/uiserver/internal/deployment/msf4j/MicroservicesRegistrar.java
pom.xml

$subject.
- Making usage values of constants defined in [`org.wso2.msf4j.internal.MSF4JConstants`](https://github.com/wso2/msf4j/blob/v2.6.0/core/src/main/java/org/wso2/msf4j/internal/MSF4JConstants.java) class "migration-safe" as those constants has been changed between MSF4J v2.5.2 and v2.6.0 versions.
- Access values of [`CHANNEL_ID`](https://github.com/wso2/msf4j/blob/v2.6.0/core/src/main/java/org/wso2/msf4j/internal/MSF4JConstants.java#L24), [`CONTEXT_PATH`](https://github.com/wso2/msf4j/blob/v2.6.0/core/src/main/java/org/wso2/msf4j/internal/MSF4JConstants.java#L25) constants in the `MSF4JConstants` class via reflection.
- If reflection fails use hard-coded values.
- Unit tests 
- passes all current tests
N/A
- Followed secure coding standards in …

Migrating to MSF4J v2.6.0

---

features/org.wso2.carbon.uiserver.feature/pom.xml
pom.xml

Following Dependencies have been updated via this PR guava - 31.1-jre
- gson - 2.9.1
- snakeyaml - 1.33
- handlebars - 4.3.1.wso2v1
- antlr - 4.11.1
Issue
https://github.com/wso2/api-manager/issues/1395

Bump 3rd party dependency versions
